### ISSUE TITLE
Cannot install zypper-upgraderepo-plugin

### ISSUE THREAD

**Issue by radoeka** [fabiomux/zypper-upgraderepo#3]
Using the following guideline: https://freeaptitude.altervista.org/projects/zypper-upgraderepo.html

It is not possible to install zypper-upgraderepo-plugin

Repository is present:

`/etc/zypp/repos.d # zyp lr  -r 9
Alias          : home_FabioMux
Name           : FabioMux's Home Project (openSUSE_Leap_15.2)
URI            : https://download.opensuse.org/repositories/home:/FabioMux/openSUSE_Leap_15.2/
Enabled        : Yes
......

/etc/zypp/repos.d # zyp in zypper-upgraderepo-plugin
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides rubygem(ruby:2.5.0:minitar) >= 0 needed by ruby2.5-rubygem-zypper-upgraderepo-1.4.0-lp152.1.1.x86_64
 Solution 1: do not install zypper-upgraderepo-plugin-1.4.0-lp152.1.1.x86_64
 Solution 2: break ruby2.5-rubygem-zypper-upgraderepo-1.4.0-lp152.1.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 
`

Available minitar is:
`# zyp se minitar
Loading repository data...
Reading installed packages...

S | Name                                    | Summary                                               | Type
--+-----------------------------------------+-------------------------------------------------------+--------
  | ruby2.5-rubygem-archive-tar-minitar     | Provides POSIX tarchive management from Ruby programs | package
`

The above package can be installed without problems:
`(1/1) Installing: ruby2.5-rubygem-archive-tar-minitar-0.5.2-lp152.3.3.x86_64 ........................................................[done]
Additional rpm output:
update-alternatives: using /usr/bin/minitar.ruby2.5-0.5.2 to provide /usr/bin/minitar (minitar) in auto mode
update-alternatives: using /usr/bin/minitar.ruby2.5-0.5.2 to provide /usr/bin/minitar-0.5.2 (minitar-0.5.2) in auto mode
update-alternatives: using /usr/bin/minitar.ruby2.5-0.5.2 to provide /usr/bin/minitar.ruby2.5 (minitar.ruby2.5) in auto mode
`

The package provides only:
`# rpm -q --provides ruby2.5-rubygem-archive-tar-minitar
ruby2.5-rubygem-archive-tar-minitar = 0.5.2-lp152.3.3
ruby2.5-rubygem-archive-tar-minitar(x86-64) = 0.5.2-lp152.3.3
rubygem(archive-tar-minitar) = 0.5.2
rubygem(ruby:2.5.0:archive-tar-minitar) = 0.5.2
rubygem(ruby:2.5.0:archive-tar-minitar:0) = 0.5.2
rubygem(ruby:2.5.0:archive-tar-minitar:0.5) = 0.5.2
rubygem(ruby:2.5.0:archive-tar-minitar:0.5.2) = 0.5.2
`

Could it be that your dependencies must be set to rubygem(ruby:2.5.0:archive-tar-minitar) ?

**Comment by fabiomux** [comment]
Hi @radoeka,
the package _archive-tar-minitar_ should be is marked as obsolete, so I linked the _minitar_ package from the  repository https://build.opensuse.org/project/show/devel:languages:ruby:extensions to mine, if you `zypper refresh` you should be able to install it correctly now.

**Comment by radoeka** [comment]
Thanks that made it work :)

`# zyp in zypper-upgraderepo-plugin
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  ruby2.5-rubygem-iniparse ruby2.5-rubygem-minitar ruby2.5-rubygem-zypper-upgraderepo zypper-upgraderepo-plugin

4 new packages to install.`
