### ISSUE TITLE
script fails on local rpm dir repo

### ISSUE THREAD

**Issue by mx1up** [fabiomux/zypper-upgraderepo#5]
Hello,

the script fails on a local rpm dir repo:
```
Error! undefined method `request_uri' for #<URI::Generic dir:/home/m/localrepo/repodata/repomd.xml>
'/usr/lib/zypper/commands/zypper-upgraderepo' exited with status 1
```
these kind of repos could be skipped?

thanks for the script
cheers

**Comment by fabiomux** [comment]
Thanks for reporting it @mx1up, may you post the repo source file?

**Comment by mx1up** [comment]
hello, thanks for the fast response!
repo file looks like this:
```
[localrepo]
name=localrepo
enabled=1
autorefresh=0
baseurl=dir:/home/m/localrepo
path=/
type=plaindir
keeppackages=0
```

**Comment by fabiomux** [comment]
Added the support for local repositories with the last release, had to refactor part of the code, but at least it will be useful to smoothly add more protocols later.
